### ISSUE TITLE
Example assembly problem

### ISSUE THREAD

**Issue by trolloos** [warbler/SharpMonoInjector#3]
So I used Visual Studio Installer to include the game development with unity workload and I even added the optional "Unity 2017.2 64-bit Editor". So then I opened the example assembly but the reference to UnityEngine was broken somehow? It did not automatically get the reference right so I added it manually "C:\Program Files\Unity\Editor\Data\Managed\UnityEngine.dll". So then the example assembly compiles fine but the .dll is only 4kb? That can not be right? It also just crashes on injection so something must be wrong. Or am I using the wrong version of the UnityEngine.dll compared to the process I am injecting to? I don't know if they should be the same?? I also tried the "Embed Interop Types" but then it won't compile because of the errors.

**Comment by Igie** [comment]
They should be the same. Reference UnityEngine.dll from the game directory, everything should work fine

**Comment by trolloos** [comment]
I fixed it by adding a reference to UnityEngine.CoreModule.dll the class object or gameobject wasn't available in UnityEngine.dll.

**Comment by jpitty03** [comment]
I'm getting the same error as Raptor2277.
ERROR: Injection Failed: GetImageFromAssembly() = 0

**Comment by JamesRoche** [comment]
Same issue here, any help?

**Comment by waltcobb** [comment]
Any updates or fixes to this?

**Comment by warbler** [comment]
Sorry about the late response. If any of you see this, please try injecting with the latest release and let me know how it goes.
