### ISSUE TITLE
ERROR: Injection failed: GetImageFromAssembly() = 0

### ISSUE THREAD

**Issue by ydididodat** [warbler/SharpMonoInjector#5]
When I try to inject, the game crashes and I get this error message.
I've looked at the source to try and find out what's causing it but it's beyond me. 
Can anyone help?

**Comment by SonicProgramming** [comment]
Same happened to me, if i find any solution, i'll tell you

**Comment by ydididodat** [comment]
The assembly is the dll you want to inject (the hack), and the image is the section of content of the assembly which contains the code.
So, it seems like this error has something to do with failing to load the code from your dll.

**Comment by warbler** [comment]
Sorry about the late response. If any of you see this, please try injecting with the latest release and let me know how it goes.
