### ISSUE TITLE
mono-2.0-bdwgc.dll

### ISSUE THREAD

**Issue by davelyons-4ob** [warbler/SharpMonoInjector#7]
Any idea how to get this to work with 'mono-2.0-bdwgc.dll'? 

I've tried adjusting the dll it looks for but no avail and doesn't find any of the processes I'm looking for.

I fails on the line..

`            if (!Native.EnumProcessModulesEx(
                process.Handle, modulePointers, 0, out var bytesNeeded, ModuleFilter.LIST_MODULES_ALL))`

and always returns 'IntPtr.Zero'.

I know this game uses 'mono-2.0-bdwgc.dll' as I've been temporarily using a stand alone injector until I can integrate this into my code.

**Comment by warbler** [comment]
There is currently a problem with injecting processes that are running the newer mono runtime. Please see [README.md](https://github.com/warbler/SharpMonoInjector/blob/master/README.md)

**Comment by BennettStaley** [comment]
`Injection failed: mono_class_get_method_from_name() returned NULL`

My Main class is exactly the same as the example dll.

**Comment by BennettStaley** [comment]
Working on my end, Risk of Rain 2. Uses `mono-2.0-bdwgc.dll`.
